/*******************************************************************************
 * widgetMappings.h
 *------------------------------------------------------------------------------
 * widget id mapping header file
 * This file was automatically generated by IngeDev. Please, do not edit!
 *
 * This file is built from 'widgetMappings.iml' file which contains the mapping
 * between "idname" and "idval" for all widgets used in your application.
 * This allows to manage the interaction between the application business part
 * (written in "C" code) and the screen resource.
 *****************************************************************************/
#ifndef __WIDGET_MAPPINGS_H
#define __WIDGET_MAPPINGS_H

#define DATE_SCREEN_EDIT_DATE 1
#define DATE_SCREEN_BUTTON_OK 2
#define GENERIC_BUTTON_CANCEL 3
#define ID_LABEL_4 4
#define ID_LABEL_5 5
#define ID_EDIT_6 6
#define ID_BUTTON_7 7
#define ID_BUTTON_8 8
#define ID_BUTTON_9 9
#define ID_LABEL_10 10
#define ID_LABEL_11 11

#endif //__WIDGET_MAPPINGS_H
